# Redis common parameters
REDIS_SESSION_TIMEOUT = 5*60

# Sentinel:CA Redis database
REDIS_CERTS_HOST = "127.0.0.1"
REDIS_CERTS_PORT = "6379"
REDIS_CERTS_PASSWORD = ""

# Sentinel:Mailpass database
REDIS_MAILPASS_HOST = "127.0.0.1"
REDIS_MAILPASS_PORT = "6379"
REDIS_MAILPASS_PASSWORD = ""

# Rate limiting [seconds]
RLIMIT_BAN_TIME = 7200
RLIMIT_WINDOW_TIME = 3600
RLIMIT_MAX_HITS = 20
